GET https://api.github.com/repos/18476305640/typora/contents/images/2022/10/28 HTTP/1.1
Authorization: token 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


###
PUT https://api.github.com/repos/18476305640/typora/contents/images/2022/10/28/1666947840416.png HTTP/1.1
Authorization: token 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
Content-Type: application/json

{"message":"Upload pictures via github-image-uploader","sha": "9f4cda923fd7403e248657e0c99b6d4cf47207b7","branch":"master","content":"Y3JlYXRlIGZpbGUgZnJvbSBJTlNPTU5JQQoKSXQncyB1cGRhdGVkISEhCgpJdCdzIHVwZGF0ZWQgYWdhaW4hIQ=="}